### ISSUE TITLE
Dead Link in wizard_battle README.md

### ISSUE THREAD

**Issue by jnario** [mikeckennedy/python-jumpstart-course-demos#16]
Just FYI, the following anchor in the `wizard_battle` app `README.md` is points to a seemingly dead page (looks like the domain gave up the ghost):

`More info: [A Guide to Python's Magic Methods] http://www.rafekettler.com/magicmethods.html)`

python-jumpstart-course-demos/apps/07_wizard_battle/you_try/README.md

**Comment by mikeckennedy** [comment]
Thanks for the heads up. I found his article in GitHub and updated the page:

[https://github.com/RafeKettler/magicmethods/blob/master/magicmethods.pdf](https://github.com/RafeKettler/magicmethods/blob/master/magicmethods.pdf)
