### ISSUE TITLE
Unicode Decode Error in 8th App - File Search App

### ISSUE THREAD

**Issue by waynewasim11** [mikeckennedy/python-jumpstart-course-demos#17]
I encountered this error when I tried to execute the 8th app - 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 17: invalid start byte
May I know how can this issue be resolved?
I am using PyCharm IDE on Windows 10 platform
![screenshot 606](https://cloud.githubusercontent.com/assets/15145099/25943152/937fa5a8-365c-11e7-8485-c5591e00f111.png)

**Comment by 1oglop1** [comment]
It might be problem wit some file or just path within the searched structure,
Try to debug it and change that string into raw string r"some_\U34nicode" string
I had similar problem with this directory name `Telephone list` and there was the sign of telephone but

**Comment by waynewasim11** [comment]
I tried searching with multiple files but it didn't work

**Comment by mikeckennedy** [comment]
This almost always happens when you hit a binary system file hidden in the folder. Thank .DS_Store on mac and .Thumbs on Windows. Can you print the file name of each file before you try to load it. That should make it clear.

**Comment by mikeckennedy** [comment]
I just updated the video with a tip on how to avoid the hidden binary files.
