### ISSUE TITLE
csv.DictReader returns OrderedDict in 3.6

### ISSUE THREAD

**Issue by DWSimmons** [mikeckennedy/python-jumpstart-course-demos#28]
Issue: Possible confusion going forward of output of csv.Dict for versions of 3.6+ as output does not match presentation

App9 "CSV Processing with the CSV module" uses csv.DictReader and the output is shown as

```<class 'dict'> {'street': '3526 HIGH ST',```
and talked as such.  While using 3.6.2 csv.DictReader returns
```<class 'collections.OrderedDict'> OrderedDict([```

I looked at CSV sourcecode for 3.5.2
line 118 -         ```d = dict(zip(self.fieldnames, row))```
and for csv.DictReader sourecode for 3.6.2
line 120 -         ```d = OrderedDict(zip(self.fieldnames, row))```

**Comment by mikeckennedy** [comment]
Thanks for reporting this @DWSimmons 

I just posted an updated video with a note about the new return type. You probably have to clear your browser cache or do a hard refresh to see the new content but will help in a pay it forward style. :)
