### ISSUE TITLE
wunderground actively refusing connection

### ISSUE THREAD

**Issue by Aceinhole** [mikeckennedy/python-jumpstart-course-demos#3]
Creating this app has ground to a halt because wunderground.com are refusing a connection through Python.
I can still go to the web and use it, but any attempt by the Python code is met with this error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda32\lib\site-packages\requests\adapters.py", line 403, in send
    timeout=timeout
  File "C:\Anaconda32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Anaconda32\lib\site-packages\requests\packages\urllib3\util\retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.wunderground.com', port=80): Max retries exceeded with url: /weather-forecast/30207 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x00000000034DE668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

Recommendations for replacement websites?

**Comment by Aceinhole** [comment]
Apparently, adding a 's' to the end of the http made all the  difference.

**Comment by mikeckennedy** [comment]
Glad you got it working. :)
