### ISSUE TITLE
'journal.py' not found

### ISSUE THREAD

**Issue by datatalking** [mikeckennedy/python-jumpstart-course-demos#33]
I bought your 2016 bundle and the journal program when I run it from pycharm and sublime it generates the error that journal.py doesn't exist?

ImportError: No module named 'journal'

I rewatched the video and it didn't look like you added code so i redownloaded the repo from github and same result.

**Comment by alt3red** [comment]
Hey datatalking, do you have some screenshots? All works for me. 
Did you try running it from the shell?

**Comment by mikeckennedy** [comment]
Hi @alt3red thanks for jumping in. 

@datatalking It looks like the working directory might not be correct. The program.py is looking for journal.py in the same level (top level) of the working directory.

**Comment by datatalking** [comment]
Hi Michael, I had to 'rebuild' the app step by step that it shows in the tutorial and was able to get the journal responding. Now it won't save the items i've added to the list.

All three files are in the Journal Directory.

I'm very new to Pycharm, so when you say working directory Michael you mean the directory that the files are saved in?

Error below.

Traceback (most recent call last):
  File "/Users/andrewschell/PycharmProjects/Journal/program.py", line 68, in <module>
    main()
  File "/Users/andrewschell/PycharmProjects/Journal/program.py", line 14, in main
    run_event_loop()
  File "/Users/andrewschell/PycharmProjects/Journal/program.py", line 48, in run_event_loop
    journal.save(journal_name, journal_data)
  File "/Users/andrewschell/PycharmProjects/Journal/journal.py", line 28, in save
    with open(filename, 'w') as fout:

# update, If I git clone the whole course repo and run it from there it works. My question is still 'why can't I retype the code and run it in my pycharm?
Feels like I am missing a step.

Otherwise, it is a helpful course so far.

FileNotFoundError: [Errno 2] No such file or directory: '/Users/andrewschell/PycharmProjects/Journal/journals/default.jrl'

**Comment by datatalking** [comment]
Hi Guys, Sorry for the delay. Here is a screenshot, note the TalkPython-Journal tab. This runs when I git clone the repo, but if I rewrite your code from scratch it seems to generate this error.

Can I sidestep this by patching it, if so let me know and I will add it or if I have some glaring error please let me know.

Michael, I'm enjoying your tutorials!

MacBookPro 2.4ghz Core i5
16gb Ram, 2Tb sshd
macOS Sierra 10.12.6
![screen shot 2018-01-13 at 9 21 28 pm](https://user-images.githubusercontent.com/11813209/34913077-0eda4e34-f8a8-11e7-99cd-7b2bd59b5bd5.png)

**Comment by 1oglop1** [comment]
@datatalking
Hi Andrew, 
Guessing from screenshot, it looks like your `journal.py` has name `Journal.py`. 
The difference is capital `J` because CASE matters. 
If you rename the file and code is still broken, please include your code repository or at least Project pane in pycharm.

**Comment by datatalking** [comment]
It runs, thank you!

I want to keep adding functionality to this script as I see multiple uses.
1. A daily journal
2. A place to ingest csv files and output json or xml for data parsing
3. A constant command line menu, that is kept in :MEMORY:
Should I put my notes here or in Projects?

Anything I work up I'm happy to share or work on as an issue.

Is there a way to add a csv or tsv import option as I have 112 action items and having python manage that would be awesome.
Also would need to add a weight or method of sorting them.

Something like

import csv
with open('eggs.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
        for row in spamreader:
              input = cmd [A]

**Comment by mikeckennedy** [comment]
Thanks @1oglop1 yes, the capitalization is very important. File names in Python become module names in code.

@datatalking sounds like a fun way to extend this app! Do share it back with us if you make it. :)
