### ISSUE TITLE
Beautiful soup is not supported/ not found

### ISSUE THREAD

**Issue by MohamedAdlyAWS** [mikeckennedy/python-jumpstart-course-demos#35]
Hello Michael, 

I am in module 5 but trying to import beautiful soup and it says there is no version available, I tried to run the setup manually and still cannot import it. 

Could you please check this out?

Thanks 

Mohamed

**Comment by MohamedAdlyAWS** [comment]
I think its not supported on python 3.6.4

**Comment by mikeckennedy** [comment]
Hi Mohamed,

I just tested this on Python 3.6.4:

`$ pip3 install bs4`

```python
>>> import bs4

>>> soup = bs4.BeautifulSoup("<div></div>", "html5lib")
```

That worked fine. It's just confusing with the module names and package names being all over the place.

**Comment by mikeckennedy** [comment]
BTW, bs4 is just a simple wrapper for https://pypi.python.org/pypi/beautifulsoup4

**Comment by MohamedAdlyAWS** [comment]
sudo pip3 install bs4
The directory '/Users/mohamdv/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/mohamdv/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting bs4
  Could not find a version that satisfies the requirement bs4 (from versions: )
No matching distribution found for bs4

**Comment by MohamedAdlyAWS** [comment]
Thank you for your response but its not working for me :(

**Comment by mikeckennedy** [comment]
Hi Mohamed,

Do you have some custom link for a private PyPI server or something? It has to be a local config issue. Here is what I got when I was looking into your issue just a minute ago:

```
macbook ➜  ~ pip3 install --user bs4
Collecting bs4
  Downloading bs4-0.0.1.tar.gz
Collecting beautifulsoup4 (from bs4)
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl
Installing collected packages: beautifulsoup4, bs4
  Running setup.py install for bs4 ... done
Successfully installed beautifulsoup4-4.6.0 bs4-0.0.1
```

**Comment by MohamedAdlyAWS** [comment]
It worked, Thanks. I had my environment messed up. Thank you again and I am enjoying your course

**Comment by mikeckennedy** [comment]
Great! Glad you got it fixed and the course is going well.
