### ISSUE TITLE
File Searcher app: Use os.scandir instead of os.listdir with Python 3.6+

### ISSUE THREAD

**Issue by rseichter** [mikeckennedy/python-jumpstart-course-demos#36]
Hello Michael. I noticed that you keep performance in mind, and also that [os.listdir()](https://docs.python.org/3/library/os.html#os.listdir) has the disadvantage of requiring the [File Searcher app](https://github.com/mikeckennedy/python-jumpstart-course-demos/tree/master/apps/08_file_searcher) to keep track of what folder a file/directory is located in. The function [os.scandir()](https://docs.python.org/3/library/os.html#os.scandir), new in Python 3.6, addresses both issues. Perhaps this is worth mentioning? I am of course aware the course material is two years old and I am uncertain if you intend to update it.

**Comment by mikeckennedy** [comment]
Thanks @rseichter I do try to keep it up-to-date but not every single detail. I'm wouldn't replace this section entirely with os.scandir(), which is cool, because part of the main lesson was recursion. I'll consider whether to add a note at the end...

**Comment by rseichter** [comment]
No worries. I found scandir() especially helpful because of the [os.DirEntry](https://docs.python.org/3/library/os.html#os.DirEntry) objects it returns (of course the built-in caching is nice as well). Name, absolute path, type--all bundled in one class and no more need to call os.path.whatever() to figure out these details.

**Comment by mikeckennedy** [comment]
Sounds great. I haven't played with it much. Thanks.
