### ISSUE TITLE
Wunderground url problem

### ISSUE THREAD

**Issue by ste032** [mikeckennedy/python-jumpstart-course-demos#37]
edit: nevermind, I didn't notice the popup at the start of video saying to check the new strings. Managed to get them by myself before I realized they were provided. Sorry for the spam.

----
 Hi all,
just a heads up, apparently wunderground doesn't let you use the zipcode to search a specific forecast via url anymore.
Also, the api's aren't free.

Regards.

**Comment by mikeckennedy** [comment]
No problem. The URL in the app still works as shown. Just the CSS selectors changed.
