### ISSUE TITLE
www.underground.com Changed their content engine?

### ISSUE THREAD

**Issue by CypSteel** [mikeckennedy/python-jumpstart-course-demos#41]
I am not seeing any id's to reference.   When I try:

https://www.wunderground.com/weather-forecast/77521?

I get a redirect to:

https://www.wunderground.com/weather/us/tx/baytown/77521

Inspecting the elements is a mess with no CSS ID tags:

![image](https://user-images.githubusercontent.com/35611200/41828972-c6e140d0-77fd-11e8-930c-1ba5a0829b57.png)

I have not been able to replicate your lesson or use the jquery part.  How would you get around this scenario?

**Comment by CypSteel** [comment]
Sure enough, after I post this issue, I see your update.  Feel free to close this issue.

**Comment by mikeckennedy** [comment]
Sorry about the confusion here. I know this web scraping project is getting long in the tooth... I'll probably rerecord it once I get the next few courses I'm working on out the door.
