### ISSUE TITLE
Escape characters in Windows?

### ISSUE THREAD

**Issue by CypSteel** [mikeckennedy/python-jumpstart-course-demos#42]
I just finished the LOL Cat Factory and I noticed Windows explorer was opening just "This PC : Documents" folder instead of my intended lolcats folder.  After doing some troubleshooting, it looks like its related to having numbers at the start of a folder and python is treating them as escape characters.  

    elif platform.system() == 'Windows':
        print(folder)
        subprocess.call(['explorer', folder])

D:/programming/10PythonApps/LoLCat\cat_pictures

The folder 10PythonApps is the issue.

Obviously I could rename my 10PythonApps folder, but how would you handle this in a real world situation where you might not have that control over where this application might be ran?  I seen several people using r to define raw literal, but others said that isn't a good practice to get into either.

Thanks for the help!

**Comment by mikeckennedy** [comment]
Hi @CypSteel , thanks for submitting the issue. I don't know what's wrong but I just cloned the repo into a similar path as you described and then ran it and everything seemed to work fine. Have a look:

![screen shot 2018-07-18 at 6 56 53 pm](https://user-images.githubusercontent.com/2035561/42916996-81688992-8abc-11e8-88bc-5a0bb74c6878.png)

I know it's not d:\programming\10apps\... but I don't see how that would affect it one way or the other. I think `C:\Users\mkennedy\Desktop\10PythonApps\apps\06_lolcat_factory\final` should be representative.

**Comment by mikeckennedy** [comment]
I've been thinking, is it possible you were running Python 2? Is this a Python 2 issue?

**Comment by CypSteel** [comment]
Appreciate you thinking about my problem.  I suspect its something to do with my D: drive as it doesn't always show up in explorer.  Might be unique to my situation.  I plan to do some testing this weekend by moving my working folder to another drive.  Thanks again for your time to validate that folders starting with numbers aren't the issue.  I assumed it was something about escaping the numbers as when I printed the path variable, it wasn't right at all.  

While I have your attention.  I love your videos so far!  I am about 75% through your 10 apps training.  I have started your Learning Pycharm, but I feel like it will be a bit dry since I am not directly learning to program.  More of a "how to use this tool" thing.  Perhaps that makes more sense a bit at a time as needed like a reference. 
 
I guess the ultimate question is this:  What is the next step I should take in solidifying my python programming skills after the 10Apps course?  Currently I am an infrastructure Solution Architect, but I wanted to branch out into the development side of things.  I can see that programming can be one of those things where you "never stop learning", but whats the path to get me to a point where I could do development for a living or develop things on my own using current best practices?  Should I focus on the Learning PyCharm course?  Should I do the "Write Pythonic Code like a Seasoned Developer"  (I have that one too!).  Or perhaps practice my skills on use cases like found here:  https://www.reddit.com/r/learnprogramming/comments/2a9ygh/1000_beginner_programming_projects_xpost/   or perhaps do you have another course to recommend like your 100 days of python?

**Comment by mikeckennedy** [comment]
Hi @CypSteel  sorry for the slow response. Been handling at lot of email / comms.

>"While I have your attention.  I love your videos so far!  I am about 75% through your 10 apps training.  I have started your Learning Pycharm, but I feel like it will be a bit dry since I am not directly learning to program.  More of a how to use this tool thing.  Perhaps that makes more sense a bit at a time as needed like a reference."

I think you'll be surprised about the PyCharm course. I thought it would be mostly as you described it. But I realized as I wrote it that each feature area needed an introduction to why it was there. So for example, the unit testing chapter has a section on what is testing, how do you do it in Python, etc. The profiling chapter has some history of profiling and general concepts on profiling.

It turned out to be basically a mini software dev course on 16 areas of software dev, just highlighting PyCharm at each step. It might actually be really good.

>"I guess the ultimate question is this:  What is the next step I should take in solidifying my python programming skills after the 10Apps course? "

Even though I said PyCharm would be awesome above, and it would, I think the biggest bang for your buck after the 10 apps course is the 100 days course. It has 33 more projects and is a pretty natural follow on from the 10 apps. There is a little, but too not much, overlap.
