### ISSUE TITLE
Weather underground url structure has changed

### ISSUE THREAD

**Issue by RuiApostolo** [mikeckennedy/python-jumpstart-course-demos#48]
It is now:

https://www.wunderground.com/weather/<country_code>[/<state>]/<city>

For example:
https://www.wunderground.com/weather/us/or/portland
https://www.wunderground.com/weather/gb/edinburgh

**Comment by mikeckennedy** [comment]
Hi @RuiApostolo Thanks for posting this. Yes, it did. We changed it in the code on github. Here's the line:

https://github.com/mikeckennedy/python-jumpstart-course-demos/blob/master/apps/05_weather_client/final/program.py#L48

The app doesn't ask for country but of course you can easily update it to do so.
