### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 330: invalid continuation byte

### ISSUE THREAD

**Issue by jonwhittlestone** [mikeckennedy/python-jumpstart-course-demos#5]
Apologies if this isn't your desired place for these kind of requests.

I am experiencing this error on lesson 8 - the file search app

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 330: invalid continuation byte`

The pycharm console gives me this with whatever text file I use.

I had initially tried download some books from Project Guttenberg and then when I encountered that error thought that it might be down to the encoding of the downloaded txt files.

I then tried the attached file, and chose 'Save As with Encoding' from Sublime Test 3. I chose UTF-8 and still received the error. I was using a Python 3 virtualenvironment by adding it in the Pycharm Python Interpreter menu as instructed.

Any assistance would be greatly appreciated. Thanks.

[The file I tried]

[lorem.txt](https://github.com/mikeckennedy/python-jumpstart-course-demos/files/441758/lorem.txt)

**Comment by mikeckennedy** [comment]
Hi Jon. I'm not sure why loading that file wasn't working for you. I just downloaded it and open it and read its text here:

<img width="762" alt="screen shot 2016-08-29 at 8 25 43 am" src="https://cloud.githubusercontent.com/assets/2035561/18056819/4f41354a-6dc2-11e6-8e9a-eb34c3517d5c.png">

I'm not sure what's going wrong. You could try posting a code here.

**Comment by mikeckennedy** [comment]
One possible error on OS X is the .DS_store file. If you're trying to iterate across the directory in that file exists in the directory, Python cannot read it. So you have to write some code to either skip it or put it into a try except block to catch the error and ignore it.

**Comment by jonwhittlestone** [comment]
Ahh yes, .DS_store file sounds like it would be the most likely culprit. Thanks Michael.

I will be at a computer in the next 48 hours to confirm.
