### ISSUE TITLE
Weather client server error

### ISSUE THREAD

**Issue by salro** [mikeckennedy/python-jumpstart-course-demos#50]
Hi.

I just completed the weather client app but regardless of my code or yours from git hub I get a server error back.
It seems to me that the api now requires the state to be in the request all the time for it to work, but not 100% sure as I am still learning.

Thanks for the great course.

**Comment by mikeckennedy** [comment]
Hi @salro Sorry about that! I don't know how it made it through getting on the server, but some reworking of the validation broken the server when a state wasn't explicitly set. Now this should work again. For example, this was crashing but now is fine:

https://weather.talkpython.fm/api/weather?city=portland&country=us&units=imperial

Thanks for letting me know and glad you're enjoying the course!
